add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration
$character
"""

[directory]
style = "bold blue"
truncate_to_repo = false

[git_branch]
symbol = " "
style = "bold purple"

[git_status]
style = "bold red"

[cmd_duration]
min_time = 1000
format = "[$duration]($style)"
style = "yellow"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[fill]
symbol = " "
